[workspace]
members = ["crates/cline-core"]

[workspace.dependencies]
reqwest = { version = "0.12.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"
tracing = "0.1.41"
futures-util = "0.3"
async-trait = "0.1.75"